apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  DB_HOST: "PREENCHER"
  DB_PORT: "PREENCHER"
  DB_USERNAME: "PREENCHER"
  DB_PASSWORD: "PREENCHER"
  DB_NAME: "PREENCHER"
