
replicaCount: 1
image:
  repository: ecr.repository.preencher
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "alb" 
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: "*.lumiere-video-processor.com"
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: 
  limits:
    cpu: 256m
    memory: 200Mi
  requests:
    cpu: 120m
    memory: 100Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# CONFIGURAR LIVENESS PROBE
livenessProbe:
  httpGet:
    path: /CONFIGURAR
    port: 3000
readinessProbe:
  httpGet:
    path: /CONFIGURAR
    port: 3000

autoscaling:
  periodSeconds: 30
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 60

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

# CONFIGURAR INFORMAÇÕES DE CERTIFICADO DO DB
env:
  NODE_ENV: production
  LOG_LEVEL: debug
  DB_SSL_CERT: -----BEGIN CERTIFICATE-----CONFIGURAR-----END CERTIFICATE-----